### ISSUE TITLE
Update fork to upstream/master

### ISSUE THREAD

**Issue by v1bri** [hunter-packages/glog#5]
@NeroBurner can you reply to my comment in https://github.com/hunter-packages/glog/pull/4 or pull in additional commits from upstream?

**Comment by v1bri** [comment]
Hey @NeroBurner, it would be a great Christmas present to get another glog update this year!

**Comment by ruslo** [comment]
@v1bri Can you clarify what you mean? As far as I can see #4 is closed. By the way this fork doesn't contain Hunter stuff like HunterGate or hunter_add_package (at least with option `WITH_GFLAGS=OFF`). Meaning there are only general fixes. If you send them upstream then `glog` can be used as is in Hunter and there is no need to maintain this intermediate repo.

**Comment by v1bri** [comment]
Thanks for the reply @ruslo. Yes that's what I would like, to use the Glog library `WITH_GFLAGS=ON`. It looks like there aren't any changes to this fork vs upstream at the moment.

As an aside, I was wondering if you had considered some way to make changes like this possible without requiring a fork to add `HunterGate` and `hunter_add_package` etc to `CMakeLists.txt`. If there's an existing bug for this request feel free to link to it and I'll move this question!

**Comment by ruslo** [comment]
> Yes that's what I would like, to use the Glog library WITH_GFLAGS=ON. It looks like there aren't any changes to this fork vs upstream at the moment

As a summary everything ok and no actions needed for now?

>  I was wondering if you had considered some way to make changes like this possible without requiring a fork to add HunterGate and hunter_add_package etc to CMakeLists.txt

There is no way to avoid adding code. One of the fundamental features of Hunter is reproducibility and at least there should be SHA1 of Hunter archive which can be seen here as an ID of environment your package need. You can think of it as a SHA1 of a git submodule.

Instead Hunter provide "disable everything" feature which can allow to not interfere with original code by just using one `HUNTER_ENABLED=OFF` option (which can be `OFF` by default):
* https://docs.hunter.sh/en/latest/overview/compatibility.html

Again as for this package there are no 3rd parties used and with few general CMake improvements (which is not related to Hunter) you can use upstream releases as is, fork not needed. As we are doing with https://github.com/nlohmann/json at this moment:
* https://github.com/ruslo/hunter/blob/8cb4814c89993c64537a1d9cc0520f171005bb7a/cmake/projects/nlohmann_json/hunter.cmake#L46-L51

**Comment by NeroBurner** [comment]
@ruslo thx for the json library, I've always used rapidjson and did wrap it to fit my needs, but nlohmann_json seems like a very good C++ json library :)

@v1bri sorry for not commenting so long. Do you need a specific feature to require an update to current master?

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/blob/v0.23.214/README.rst
